name: CI-CD Example
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  my_first_job:
    runs-on: ubuntu-latest

    steps:

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Show java version
      run: 'java -version'

    - name: Show directory
      run: pwd

    - name: List of files
      run: 'ls -al ../'

    - name: Install dependencies
      run: 'mvn compile'

    - name: Build App
      run: 'mvn package -DskipTests'
      
    
